name: Backend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run linting
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test

  build:
    needs: [lint, test]
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: staging

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run:  docker build --tag=111931375561.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7} .

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: 111931375561.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push Docker image
        run: docker push 111931375561.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: staging

    defaults:
      run:
        working-directory: starter/backend/k8s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Config eks
        run: aws eks update-kubeconfig --name cluster

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy to Kubernetes
        run: |
          kustomize edit set image backend=111931375561.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA::7}
          kustomize build | kubectl apply -f -